### ISSUE TITLE
fs is imported by node_modules/fitbit-i18n/index.js, but could not be resolved

### ISSUE THREAD

**Issue by julianschmuckli** [gregoiresage/fitbit-i18n#1]
I have a problem with the library. I use the version 0.1.2. But when I want to build my app, I just get the following error message:

> [21:50:59][error][companion] fs is imported by node_modules/fitbit-i18n/index.js, but could not be resolved
> [21:50:59][error][companion] Error: Compile failed.
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! app@0.1.0 build: `fitbit-build`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the app@0.1.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /Users/julian/.npm/_logs/2019-03-06T20_50_59_379Z-debug.log

I have already checked the documentation from Fitbit to find out if there were any changes to the file system (fs) API, but there weren't any changes.

Do you have any ideas how to solve this problem?

**Comment by gregoiresage** [comment]
The module is not supposed to be imported on the companion side. It is just for the app (watch) side.
There is no fs api on the companion side
